name: deploy dev
on:
  workflow_dispatch:

jobs:
  deploy-test:
    name: ${{ matrix.step }}
    runs-on: ubuntu-latest
    environment: dev
    env:
      YARN_ENABLE_SCRIPTS: false
      GH_PAT: ${{ secrets.GH_PAT }}
      GH_RELEASE_GITHUB_API_TOKEN: ${{ secrets.GH_PAT }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'yarn'

      - name: install deps
        run: |
          yarn install

      - name: build
        run: |
          yarn build

      - name: deploy test
        uses: appleboy/scp-action@master
        with:
          username: ubuntu
          host: ${{ secrets.HOST }}
          port: 22
          key: ${{ secrets.KEY }}
          source: ${{ github.workspace }}/dist
          target: '/mnt/valid'
          strip_components: 3
          rm: true
